#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CrabChampions

#include "Basic.hpp"

#include "CrabChampions_structs.hpp"
#include "AIModule_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Slate_structs.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function CrabChampions.CrabGameStateUI.OnChatTextCommitted
// 0x0020 (0x0020 - 0x0000)
struct CrabGameStateUI_OnChatTextCommitted final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	ETextCommit                                   CommitMethod;                                      // 0x0018(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_CrabGameStateUI_OnChatTextCommitted;

// Function CrabChampions.CrabGM.DebugGoToIsland
// 0x0004 (0x0004 - 0x0000)
struct CrabGM_DebugGoToIsland final
{
public:
	int32                                         IslandToGoTo;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabGM_DebugGoToIsland;

// Function CrabChampions.CrabGM.OnNavigationGenerationFinished
// 0x0008 (0x0008 - 0x0000)
struct CrabGM_OnNavigationGenerationFinished final
{
public:
	class ANavigationData*                        NavData;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabGM_OnNavigationGenerationFinished;

// Function CrabChampions.CrabHarvestArea.MulticastOnCountdownUpdated
// 0x0001 (0x0001 - 0x0000)
struct CrabHarvestArea_MulticastOnCountdownUpdated final
{
public:
	uint8                                         PercentComplete;                                   // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabHarvestArea_MulticastOnCountdownUpdated;

// Function CrabChampions.CrabC.ClientKnockback
// 0x0010 (0x0010 - 0x0000)
struct CrabC_ClientKnockback final
{
public:
	struct FVector_NetQuantizeNormal              Dir;                                               // 0x0000(0x000C)(ConstParm, Parm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Strength;                                          // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabC_ClientKnockback;

// Function CrabChampions.CrabC.OnRep_DebuffState
// 0x0014 (0x0014 - 0x0000)
struct CrabC_OnRep_DebuffState final
{
public:
	struct FCrabDebuffState                       PreviousDebuffState;                               // 0x0000(0x0014)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabC_OnRep_DebuffState;

// Function CrabChampions.CrabC.ServerClientAuthoritativeMove
// 0x0050 (0x0050 - 0x0000)
struct CrabC_ServerClientAuthoritativeMove final
{
public:
	struct FClientAuthoritativeMoveData           MoveData;                                          // 0x0000(0x0050)(ConstParm, Parm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabC_ServerClientAuthoritativeMove;

// Function CrabChampions.CrabC.ServerSpawnCosmeticProjectile
// 0x0048 (0x0048 - 0x0000)
struct CrabC_ServerSpawnCosmeticProjectile final
{
public:
	struct FCrabProjectileInfo                    ProjectileInfo;                                    // 0x0000(0x0030)(ConstParm, Parm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	class AActor*                                 ProjectileOwner;                                   // 0x0030(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector_NetQuantize                    StartLoc;                                          // 0x0038(0x000C)(ConstParm, Parm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_CrabC_ServerSpawnCosmeticProjectile;

// Function CrabChampions.CrabEnemyC.MulticastSpawnMirroredProjectile
// 0x0008 (0x0008 - 0x0000)
struct CrabEnemyC_MulticastSpawnMirroredProjectile final
{
public:
	class ACrabC*                                 DamagingC;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabEnemyC_MulticastSpawnMirroredProjectile;

// Function CrabChampions.CrabDestructible.MulticastAddLeak
// 0x000C (0x000C - 0x0000)
struct CrabDestructible_MulticastAddLeak final
{
public:
	struct FVector_NetQuantize                    DamageLoc;                                         // 0x0000(0x000C)(ConstParm, Parm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabDestructible_MulticastAddLeak;

// Function CrabChampions.CrabDestructible.MulticastExplode
// 0x0008 (0x0008 - 0x0000)
struct CrabDestructible_MulticastExplode final
{
public:
	class ACrabC*                                 ExplodingC;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabDestructible_MulticastExplode;

// Function CrabChampions.CrabDestructible.OnComponentHit
// 0x00B0 (0x00B0 - 0x0000)
struct CrabDestructible_OnComponentHit final
{
public:
	class UPrimitiveComponent*                    HitComponent;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                NormalImpulse;                                     // 0x0018(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHitResult                             Hit;                                               // 0x0024(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_CrabDestructible_OnComponentHit;

// Function CrabChampions.CrabEnemyAIC.OnReceiveMoveCompleted
// 0x0008 (0x0008 - 0x0000)
struct CrabEnemyAIC_OnReceiveMoveCompleted final
{
public:
	struct FAIRequestID                           RequestID;                                         // 0x0000(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPathFollowingResult                          Result;                                            // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_CrabEnemyAIC_OnReceiveMoveCompleted;

// Function CrabChampions.CrabKeyBindRowUI.OnPressedControllerKeySelector
// 0x0020 (0x0020 - 0x0000)
struct CrabKeyBindRowUI_OnPressedControllerKeySelector final
{
public:
	struct FInputChord                            SelectedKey;                                       // 0x0000(0x0020)(Parm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabKeyBindRowUI_OnPressedControllerKeySelector;

// Function CrabChampions.CrabKeyBindRowUI.OnPressedKeyboardKeySelector
// 0x0020 (0x0020 - 0x0000)
struct CrabKeyBindRowUI_OnPressedKeyboardKeySelector final
{
public:
	struct FInputChord                            SelectedKey;                                       // 0x0000(0x0020)(Parm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabKeyBindRowUI_OnPressedKeyboardKeySelector;

// Function CrabChampions.CrabLM.MulticastPlayOneShotFX
// 0x0020 (0x0020 - 0x0000)
struct CrabLM_MulticastPlayOneShotFX final
{
public:
	class UNiagaraSystem*                         FXToPlay;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USoundCue*                              SoundToPlay;                                       // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                SpawnLoc;                                          // 0x0010(0x000C)(ConstParm, Parm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_CrabLM_MulticastPlayOneShotFX;

// Function CrabChampions.CrabLM.MulticastSpawnCosmeticProjectile
// 0x0048 (0x0048 - 0x0000)
struct CrabLM_MulticastSpawnCosmeticProjectile final
{
public:
	struct FCrabProjectileInfo                    ProjectileInfo;                                    // 0x0000(0x0030)(ConstParm, Parm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	class AActor*                                 ProjectileOwner;                                   // 0x0030(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector_NetQuantize                    StartLoc;                                          // 0x0038(0x000C)(ConstParm, Parm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_CrabLM_MulticastSpawnCosmeticProjectile;

// Function CrabChampions.CrabPC.ClientInventoryEvent
// 0x0010 (0x0010 - 0x0000)
struct CrabPC_ClientInventoryEvent final
{
public:
	class FString                                 InventoryEventMessage;                             // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPC_ClientInventoryEvent;

// Function CrabChampions.CrabPC.ClientNotifyDamageDealt
// 0x0050 (0x0050 - 0x0000)
struct CrabPC_ClientNotifyDamageDealt final
{
public:
	struct FCrabDamageInfo                        DamageInfo;                                        // 0x0000(0x0048)(ConstParm, Parm, ReferenceParm, NativeAccessSpecifierPublic)
	ECrabDamageHitType                            DamageHitType;                                     // 0x0048(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_CrabPC_ClientNotifyDamageDealt;

// Function CrabChampions.CrabPC.ClientOnClearedIsland
// 0x0001 (0x0001 - 0x0000)
struct CrabPC_ClientOnClearedIsland final
{
public:
	bool                                          bWasFlawlessClear;                                 // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPC_ClientOnClearedIsland;

// Function CrabChampions.CrabPC.ClientOnEliminated
// 0x0010 (0x0010 - 0x0000)
struct CrabPC_ClientOnEliminated final
{
public:
	class FString                                 EliminationCause;                                  // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPC_ClientOnEliminated;

// Function CrabChampions.CrabPC.ClientOnEnteredPortal
// 0x0050 (0x0050 - 0x0000)
struct CrabPC_ClientOnEnteredPortal final
{
public:
	struct FCrabNextIslandInfo                    NextIslandInfo;                                    // 0x0000(0x0048)(ConstParm, Parm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          bSaveAutoSave;                                     // 0x0048(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_CrabPC_ClientOnEnteredPortal;

// Function CrabChampions.CrabPC.ClientOnInteractedWithKeyTotem
// 0x0008 (0x0008 - 0x0000)
struct CrabPC_ClientOnInteractedWithKeyTotem final
{
public:
	class ACrabTotem*                             KeyTotem;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPC_ClientOnInteractedWithKeyTotem;

// Function CrabChampions.CrabPC.ClientOnPickedUpPickup
// 0x0010 (0x0010 - 0x0000)
struct CrabPC_ClientOnPickedUpPickup final
{
public:
	class UCrabPickupDA*                          PickupDA;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Level;                                             // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_CrabPC_ClientOnPickedUpPickup;

// Function CrabChampions.CrabPC.ClientOnReceivedChatMessage
// 0x0018 (0x0018 - 0x0000)
struct CrabPC_ClientOnReceivedChatMessage final
{
public:
	class ACrabPS*                                PS;                                                // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ChatMessage;                                       // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPC_ClientOnReceivedChatMessage;

// Function CrabChampions.CrabPC.ClientOnTookDamage
// 0x0001 (0x0001 - 0x0000)
struct CrabPC_ClientOnTookDamage final
{
public:
	ECrabDamageHitType                            DamageHitType;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPC_ClientOnTookDamage;

// Function CrabChampions.CrabPC.ClientOnUpdatedOutOfBoundsState
// 0x0001 (0x0001 - 0x0000)
struct CrabPC_ClientOnUpdatedOutOfBoundsState final
{
public:
	ECrabOutOfBoundsState                         NewOutOfBoundsState;                               // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPC_ClientOnUpdatedOutOfBoundsState;

// Function CrabChampions.CrabPC.ClientSetIsCharacterInputEnabled
// 0x0001 (0x0001 - 0x0000)
struct CrabPC_ClientSetIsCharacterInputEnabled final
{
public:
	bool                                          bNewIsCharacterInputEnabled;                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPC_ClientSetIsCharacterInputEnabled;

// Function CrabChampions.CrabPC.ServerRestoreAutoSave
// 0x0168 (0x0168 - 0x0000)
struct CrabPC_ServerRestoreAutoSave final
{
public:
	struct FCrabAutoSave                          AutoSave;                                          // 0x0000(0x0168)(ConstParm, Parm, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPC_ServerRestoreAutoSave;

// Function CrabChampions.CrabPC.ServerSendChatMessage
// 0x0010 (0x0010 - 0x0000)
struct CrabPC_ServerSendChatMessage final
{
public:
	class FString                                 ChatMessage;                                       // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPC_ServerSendChatMessage;

// Function CrabChampions.CrabPC.ServerSpawnKeyTotemPickup
// 0x0010 (0x0010 - 0x0000)
struct CrabPC_ServerSpawnKeyTotemPickup final
{
public:
	class ACrabTotem*                             KeyTotem;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCrabPickupDA*                          PickupToSpawn;                                     // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPC_ServerSpawnKeyTotemPickup;

// Function CrabChampions.CrabPC.ServerUploadLobbyStats
// 0x0058 (0x0058 - 0x0000)
struct CrabPC_ServerUploadLobbyStats final
{
public:
	struct FCrabLobbyStats                        LobbyStats;                                        // 0x0000(0x0058)(ConstParm, Parm, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPC_ServerUploadLobbyStats;

// Function CrabChampions.CrabPhysicsActor.OnComponentHit
// 0x00B0 (0x00B0 - 0x0000)
struct CrabPhysicsActor_OnComponentHit final
{
public:
	class UPrimitiveComponent*                    HitComponent;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                NormalImpulse;                                     // 0x0018(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHitResult                             Hit;                                               // 0x0024(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_CrabPhysicsActor_OnComponentHit;

// Function CrabChampions.CrabPlayerC.ClientPrePortal
// 0x0008 (0x0008 - 0x0000)
struct CrabPlayerC_ClientPrePortal final
{
public:
	class ACrabPortal*                            Portal;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ClientPrePortal;

// Function CrabChampions.CrabPlayerC.ClientTeleport
// 0x0010 (0x0010 - 0x0000)
struct CrabPlayerC_ClientTeleport final
{
public:
	struct FVector_NetQuantize                    Loc;                                               // 0x0000(0x000C)(ConstParm, Parm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Yaw;                                               // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ClientTeleport;

// Function CrabChampions.CrabPlayerC.MulticastAbility
// 0x000C (0x000C - 0x0000)
struct CrabPlayerC_MulticastAbility final
{
public:
	struct FVector_NetQuantize                    InAbilityTelegraphLoc;                             // 0x0000(0x000C)(ConstParm, Parm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_MulticastAbility;

// Function CrabChampions.CrabPlayerC.MulticastDash
// 0x0001 (0x0001 - 0x0000)
struct CrabPlayerC_MulticastDash final
{
public:
	ECrabInputDir                                 DashDir;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_MulticastDash;

// Function CrabChampions.CrabPlayerC.MulticastFlip
// 0x0001 (0x0001 - 0x0000)
struct CrabPlayerC_MulticastFlip final
{
public:
	ECrabInputDir                                 FlipDir;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_MulticastFlip;

// Function CrabChampions.CrabPlayerC.OnRep_PingLoc
// 0x000C (0x000C - 0x0000)
struct CrabPlayerC_OnRep_PingLoc final
{
public:
	struct FVector_NetQuantize                    PreviousPingLoc;                                   // 0x0000(0x000C)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_OnRep_PingLoc;

// Function CrabChampions.CrabPlayerC.ServerAbility
// 0x000C (0x000C - 0x0000)
struct CrabPlayerC_ServerAbility final
{
public:
	struct FVector_NetQuantize                    InAbilityTelegraphLoc;                             // 0x0000(0x000C)(ConstParm, Parm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ServerAbility;

// Function CrabChampions.CrabPlayerC.ServerApplyEnhancement
// 0x0008 (0x0008 - 0x0000)
struct CrabPlayerC_ServerApplyEnhancement final
{
public:
	class UCrabInventoryDA*                       InventoryDA;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ServerApplyEnhancement;

// Function CrabChampions.CrabPlayerC.ServerDash
// 0x0001 (0x0001 - 0x0000)
struct CrabPlayerC_ServerDash final
{
public:
	ECrabInputDir                                 DashDir;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ServerDash;

// Function CrabChampions.CrabPlayerC.ServerDealDamage
// 0x0010 (0x0010 - 0x0000)
struct CrabPlayerC_ServerDealDamage final
{
public:
	TArray<struct FCrabDamageInfo>                DamageInfoArray;                                   // 0x0000(0x0010)(ConstParm, Parm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ServerDealDamage;

// Function CrabChampions.CrabPlayerC.ServerDropPickup
// 0x0028 (0x0028 - 0x0000)
struct CrabPlayerC_ServerDropPickup final
{
public:
	class UCrabPickupDA*                          PickupDA;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCrabInventoryInfo                     InventoryInfo;                                     // 0x0008(0x0020)(ConstParm, Parm, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ServerDropPickup;

// Function CrabChampions.CrabPlayerC.ServerFlip
// 0x0001 (0x0001 - 0x0000)
struct CrabPlayerC_ServerFlip final
{
public:
	ECrabInputDir                                 FlipDir;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ServerFlip;

// Function CrabChampions.CrabPlayerC.ServerInteract
// 0x0008 (0x0008 - 0x0000)
struct CrabPlayerC_ServerInteract final
{
public:
	class ACrabInteractable*                      ActorToInteractWith;                               // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ServerInteract;

// Function CrabChampions.CrabPlayerC.ServerPing
// 0x000C (0x000C - 0x0000)
struct CrabPlayerC_ServerPing final
{
public:
	struct FVector_NetQuantize                    InPingLoc;                                         // 0x0000(0x000C)(ConstParm, Parm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ServerPing;

// Function CrabChampions.CrabPlayerC.ServerSalvage
// 0x0008 (0x0008 - 0x0000)
struct CrabPlayerC_ServerSalvage final
{
public:
	class ACrabInteractPickup*                    PickupToSalvage;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ServerSalvage;

// Function CrabChampions.CrabPlayerC.ServerSetActiveInteractable
// 0x0008 (0x0008 - 0x0000)
struct CrabPlayerC_ServerSetActiveInteractable final
{
public:
	class ACrabInteractable*                      NewActiveInteractable;                             // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ServerSetActiveInteractable;

// Function CrabChampions.CrabPlayerC.ServerUpgradeTotemPurchase
// 0x0010 (0x0010 - 0x0000)
struct CrabPlayerC_ServerUpgradeTotemPurchase final
{
public:
	int32                                         UpgradeCost;                                       // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCrabInventoryDA*                       InventoryDA;                                       // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPlayerC_ServerUpgradeTotemPurchase;

// Function CrabChampions.CrabPS.ServerEquipCosmetics
// 0x0008 (0x0008 - 0x0000)
struct CrabPS_ServerEquipCosmetics final
{
public:
	class UMaterialInterface*                     NewCrabSkin;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPS_ServerEquipCosmetics;

// Function CrabChampions.CrabPS.ServerEquipInventory
// 0x0018 (0x0018 - 0x0000)
struct CrabPS_ServerEquipInventory final
{
public:
	class UCrabWeaponDA*                          NewWeaponDA;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCrabAbilityDA*                         NewAbilityDA;                                      // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCrabMeleeDA*                           NewMeleeDA;                                        // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPS_ServerEquipInventory;

// Function CrabChampions.CrabPS.ServerIncrementNumInventorySlots
// 0x0008 (0x0008 - 0x0000)
struct CrabPS_ServerIncrementNumInventorySlots final
{
public:
	ECrabPickupType                               PickupType;                                        // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Cost;                                              // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPS_ServerIncrementNumInventorySlots;

// Function CrabChampions.CrabPS.ServerRefreshAccount
// 0x000C (0x000C - 0x0000)
struct CrabPS_ServerRefreshAccount final
{
public:
	ECrabRank                                     NewAccountRank;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         NewAccountLevel;                                   // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NewKeys;                                           // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPS_ServerRefreshAccount;

// Function CrabChampions.CrabPS.ServerRemoveAbilityMod
// 0x0001 (0x0001 - 0x0000)
struct CrabPS_ServerRemoveAbilityMod final
{
public:
	ECrabAbilityModType                           AbilityModType;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPS_ServerRemoveAbilityMod;

// Function CrabChampions.CrabPS.ServerRemoveMeleeMod
// 0x0001 (0x0001 - 0x0000)
struct CrabPS_ServerRemoveMeleeMod final
{
public:
	ECrabMeleeModType                             MeleeModType;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPS_ServerRemoveMeleeMod;

// Function CrabChampions.CrabPS.ServerRemovePerk
// 0x0001 (0x0001 - 0x0000)
struct CrabPS_ServerRemovePerk final
{
public:
	ECrabPerkType                                 PerkType;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPS_ServerRemovePerk;

// Function CrabChampions.CrabPS.ServerRemoveRelic
// 0x0001 (0x0001 - 0x0000)
struct CrabPS_ServerRemoveRelic final
{
public:
	ECrabRelicType                                RelicType;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPS_ServerRemoveRelic;

// Function CrabChampions.CrabPS.ServerRemoveWeaponMod
// 0x0001 (0x0001 - 0x0000)
struct CrabPS_ServerRemoveWeaponMod final
{
public:
	ECrabWeaponModType                            WeaponModType;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPS_ServerRemoveWeaponMod;

// Function CrabChampions.CrabPS.ServerSetAbilityDA
// 0x0008 (0x0008 - 0x0000)
struct CrabPS_ServerSetAbilityDA final
{
public:
	class UCrabAbilityDA*                         NewAbilityDA;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPS_ServerSetAbilityDA;

// Function CrabChampions.CrabPS.ServerSetMeleeDA
// 0x0008 (0x0008 - 0x0000)
struct CrabPS_ServerSetMeleeDA final
{
public:
	class UCrabMeleeDA*                           NewMeleeDA;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPS_ServerSetMeleeDA;

// Function CrabChampions.CrabPS.ServerSetWeaponDA
// 0x0008 (0x0008 - 0x0000)
struct CrabPS_ServerSetWeaponDA final
{
public:
	class UCrabWeaponDA*                          NewWeaponDA;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabPS_ServerSetWeaponDA;

// Function CrabChampions.CrabShopPedestal.MulticastInitPedestalInfo
// 0x000C (0x000C - 0x0000)
struct CrabShopPedestal_MulticastInitPedestalInfo final
{
public:
	struct FCrabPedestalInfo                      NewPedestalInfo;                                   // 0x0000(0x000C)(ConstParm, Parm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabShopPedestal_MulticastInitPedestalInfo;

// Function CrabChampions.CrabSliderUI.OnMainSliderValueChanged
// 0x0004 (0x0004 - 0x0000)
struct CrabSliderUI_OnMainSliderValueChanged final
{
public:
	float                                         Value;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabSliderUI_OnMainSliderValueChanged;

// Function CrabChampions.CrabSpectatorC.ClientInitSpectatorC
// 0x0008 (0x0008 - 0x0000)
struct CrabSpectatorC_ClientInitSpectatorC final
{
public:
	class ACrabPlayerC*                           EliminatedPlayerToSpectate;                        // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabSpectatorC_ClientInitSpectatorC;

// Function CrabChampions.CrabSpectatorC.ClientSpectatePlayer
// 0x0010 (0x0010 - 0x0000)
struct CrabSpectatorC_ClientSpectatePlayer final
{
public:
	class ACrabPlayerC*                           PlayerToSpectate;                                  // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bShowSpectatingUI;                                 // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_CrabSpectatorC_ClientSpectatePlayer;

// Function CrabChampions.CrabVideoMenuUI.SetAntiAliasingType
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetAntiAliasingType final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetAntiAliasingType;

// Function CrabChampions.CrabVideoMenuUI.SetCameraShake
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetCameraShake final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetCameraShake;

// Function CrabChampions.CrabVideoMenuUI.SetDamageNumbers
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetDamageNumbers final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetDamageNumbers;

// Function CrabChampions.CrabVideoMenuUI.SetDisplayMode
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetDisplayMode final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetDisplayMode;

// Function CrabChampions.CrabVideoMenuUI.SetFieldOfView
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetFieldOfView final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetFieldOfView;

// Function CrabChampions.CrabVideoMenuUI.SetFPSLimit
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetFPSLimit final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetFPSLimit;

// Function CrabChampions.CrabVideoMenuUI.SetGraphicsQuality
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetGraphicsQuality final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetGraphicsQuality;

// Function CrabChampions.CrabVideoMenuUI.SetHitmarkers
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetHitmarkers final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetHitmarkers;

// Function CrabChampions.CrabVideoMenuUI.SetMotionBlur
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetMotionBlur final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetMotionBlur;

// Function CrabChampions.CrabVideoMenuUI.SetPauseWhenLosingFocus
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetPauseWhenLosingFocus final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetPauseWhenLosingFocus;

// Function CrabChampions.CrabVideoMenuUI.SetResolution
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetResolution final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetResolution;

// Function CrabChampions.CrabVideoMenuUI.SetResolutionQuality
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetResolutionQuality final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetResolutionQuality;

// Function CrabChampions.CrabVideoMenuUI.SetSharpening
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetSharpening final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetSharpening;

// Function CrabChampions.CrabVideoMenuUI.SetShowFPS
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetShowFPS final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetShowFPS;

// Function CrabChampions.CrabVideoMenuUI.SetTextChatVisibility
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetTextChatVisibility final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetTextChatVisibility;

// Function CrabChampions.CrabVideoMenuUI.SetVSync
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetVSync final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetVSync;

// Function CrabChampions.CrabVideoMenuUI.SetWeaponEffects
// 0x0010 (0x0010 - 0x0000)
struct CrabVideoMenuUI_SetWeaponEffects final
{
public:
	class FString                                 NewSelection;                                      // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabVideoMenuUI_SetWeaponEffects;

// Function CrabChampions.CrabWeapon.ServerSetIsReloading
// 0x0001 (0x0001 - 0x0000)
struct CrabWeapon_ServerSetIsReloading final
{
public:
	bool                                          bNewIsReloading;                                   // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrabWeapon_ServerSetIsReloading;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
